[Unit]
Wants=zerolab-network.service
After=zerolab-network.service

[Service]
EnvironmentFile=-/etc/default/zerolab-network
ExecStartPre=/usr/local/libexec/zerolab-network-config validate-sender /etc/default/zerolab-network
